- name: "prepare offline docker {{ insecure_registry }}/{{downloaditem.value.name}}"
  docker_image:
    name: "{{ insecure_registry }}/{{downloaditem.value.name}}"
    tag: "{{downloaditem.value.tag}}"
  register: localregistry
  ignore_errors: yes

- name: "download from pulibc repo {{downloaditem.value.publicrepo}}"
  docker_image:
    name: "{{downloaditem.value.publicrepo}}"
    tag: "{{downloaditem.value.tag}}"
  register: publicregistry
  ignore_errors: yes
  when: localregistry|failed

- name: "Tag and push to private docker registry {{ insecure_registry }}/{{downloaditem.value.name}} to localhost:5000/{{downloaditem.value.name}}"
  docker_image:
    name: "{{ insecure_registry }}/{{downloaditem.value.name}}"
    repository: "localhost:5000/{{downloaditem.value.name}}"
    tag: "{{downloaditem.value.tag}}"
    push: yes
  when: not localregistry|failed
 
- name: "Tag and push to public docker registry {{downloaditem.value.publicrepo}} to localhost:5000/{{downloaditem.value.name}}"
  docker_image:
    name: "{{downloaditem.value.publicrepo}}"
    repository: "localhost:5000/{{downloaditem.value.name}}"
    tag: "{{downloaditem.value.tag}}"
    push: yes
  when: localregistry|failed