- name: "Tag and push from private to localhost docker registry {{ insecure_registry }}/{{downloaditem.value.name}} to localhost:5000/{{downloaditem.value.name}}"
  docker_image:
    name: "{{ insecure_registry }}/{{downloaditem.value.name}}"
    repository: "localhost:5000/{{downloaditem.value.name}}"
    tag: "{{downloaditem.value.tag}}"
    push: yes
  register: localregistry
  ignore_errors: yes


- name: "Tag and push from public to localhost docker registry {{downloaditem.value.publicrepo}} to localhost:5000/{{downloaditem.value.name}}"
  docker_image:
    name: "{{downloaditem.value.publicrepo}}"
    repository: "localhost:5000/{{downloaditem.value.name}}"
    tag: "{{downloaditem.value.tag}}"
    push: yes
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
  when: localregistry|failed
  
- name: "Tag and push from public to private docker registry {{downloaditem.value.publicrepo}} to {{ insecure_registry }}/{{downloaditem.value.name}}"
  docker_image:
    name: "{{downloaditem.value.publicrepo}}"
    repository: "{{ insecure_registry }}/{{downloaditem.value.name}}"
    tag: "{{downloaditem.value.tag}}"
    push: yes
  when: localregistry|failed