- name: Create kubernetes config hyc/hycapp/das directory
  file:
    path: "{{ kube_config_dir }}/hyc/hycapp/das"
    state: directory
    owner: kube
  when: inventory_hostname == groups['kube-master'][0]

- name: das | Create das manifest
  template:
    src: das.yaml.j2
    dest: "{{ kube_config_dir }}/hyc/hycapp/das/das.yml"
  when: inventory_hostname == groups['kube-master'][0]

- name: das | Start das Resources
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/hyc/hycapp/das/das.yml"
    state: 'present'
  when: inventory_hostname == groups['kube-master'][0]