- name: mds | Create mds manifest
  template:
    src: kubernetes.yaml.j2
    dest: "{{ kube_config_dir }}/hyc/hycapp/mdx/mds.yml"
  when: inventory_hostname == groups['kube-master'][0]

- name: mds | Start mds Resources
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/hyc/hycapp/mdx/mds.yml"
    state: 'present'
  when: inventory_hostname == groups['kube-master'][0]
  
- include: template-and-create.yml
  vars: 
    targethost: "{{item}}"
  ignore_errors: yes
  with_items: "{{ groups['access-layer'] }}"
  when: inventory_hostname == groups['kube-master'][0]