- name: Create kubernetes config hyc/hycapp/hycindexsave directory
  file:
    path: "{{ kube_config_dir }}/hyc/hycapp/hycindexsave"
    state: directory
    owner: kube
  when: inventory_hostname == groups['kube-master'][0]

- name: hycindexsave | Create hycindexsave manifest
  template:
    src: hycindexsave.yaml.j2
    dest: "{{ kube_config_dir }}/hyc/hycapp/hycindexsave/hycindexsave.yml"
  when: inventory_hostname == groups['kube-master'][0]

- name: hycindexsave | Start hycindexsave Resources
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/hyc/hycapp/hycindexsave/hycindexsave.yml"
    state: 'present'
  when: inventory_hostname == groups['kube-master'][0]
  ignore_errors: yes