---

- name: prepare offline docker images
  docker_image:
    name: "{{ insecure_registry }}/{{item.value.name}}"
    tag: "{{item.value.tag}}"
  register: localregistry
  notify:
    - download from pulibc repo
    - etcd | reload systemd

- name: download from pulibc repo
  docker_image:
    name: "{{item.value.publicrepo}}"
    tag: "{{item.value.tag}}"
  register: publicregistry
  notify:
    - Tag and push to public docker registry
  when: localregistry.failed|bool
    
- name: Tag and push to private docker registry
  docker_image:
    name: "{{ insecure_registry }}/{{item.value.name}}"
    repository: "localhost:5000/{{item.value.name}}"
    tag: "{{item.value.tag}}"
    push: yes
  when: not localregistry.failed|bool

- name: Tag and push to private docker registry
  docker_image:
    name: "{{ insecure_registry }}/{{item.value.name}}"
    repository: "localhost:5000/{{item.value.name}}"
    tag: "{{item.value.tag}}"
    push: yes
  when: localregistry.failed|bool and publicregistry.returned == 'success'