- name: Create kubernetes config hyc/hycapp/sss directory
  file:
    path: "{{ kube_config_dir }}/hyc/hycapp/sss"
    state: directory
    owner: kube
  when: inventory_hostname == groups['kube-master'][0]

- name: sss | Create sss manifest
  template:
    src: kubernetes.yaml.j2
    dest: "{{ kube_config_dir }}/hyc/hycapp/sss/sss.yml"
  when: inventory_hostname == groups['kube-master'][0]

- name: sss | Start sss Resources
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/hyc/hycapp/sss/sss.yml"
    state: 'present'
  when: inventory_hostname == groups['kube-master'][0]