- name: Create kubernetes config hyc/hycapp/ingress directory
  file:
    path: "{{ kube_config_dir }}/hyc/hycapp/ingress"
    state: directory
    owner: kube
  when: inventory_hostname == groups['kube-master'][0]

- name: ingress | Create ingress manifest
  template:
    src: ingress-default.yaml.j2
    dest: "{{ kube_config_dir }}/hyc/hycapp/ingress/ingress-default.yml"
  when: inventory_hostname == groups['kube-master'][0]

- name: ingress | Start ingress Resources
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/hyc/hycapp/ingress/ingress-default.yml"
    state: 'present'
  when: inventory_hostname == groups['kube-master'][0]
  
- include: template-and-create.yml
  vars: 
    targethost: "{{item}}"
  ignore_errors: yes
  with_items: "{{ groups['access-layer'] }}"
  when: inventory_hostname == groups['kube-master'][0]