- name: groupservice | Create groupservice manifest
  template:
    src: kubernetes.yaml.j2
    dest: "{{ kube_config_dir }}/hyc/hycapp/groupservice/groupservice.yml"
  when: inventory_hostname == groups['kube-master'][0]

- name: groupservice | Start groupservice Resources
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/hyc/hycapp/groupservice/groupservice.yml"
    state: 'present'
  when: inventory_hostname == groups['kube-master'][0]